version: '3'
services:
    tgi:
        command: '--model-id gpt2'
        image: 'ghcr.io/huggingface/text-generation-inference:1.0.2'
        ports:
            - '8281:80'
        shm_size: 1g    # Recommended is 40% of RAM available
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                        - capabilities: [gpu]
